[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.75"
console_error_panic_hook = "0.1.6"
console_log = "1.0.0"
fast_paths = { git = "https://github.com/easbar/fast_paths" }
geo = { git = "https://github.com/dabreegster/geo", branch = "boolops_and_linesplit" }
geojson = { git = "https://github.com/georust/geojson", features = ["geo-types"] }
log = "0.4.20"
osm-reader = { git = "https://github.com/a-b-street/osm-reader" }
route-snapper-graph = { git = "https://github.com/dabreegster/route_snapper", branch = "no_osm2streets" }
serde = "1.0.188"
serde_json = "1.0.105"
serde-wasm-bindgen = "0.6.0"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["console"] }
bincode = "1.3.3"
contour = "0.12.0"
rstar = "0.11.0"
web-time = "1.0.0"

# For local development. wasm-opt costs about 40s and appears to have no difference at runtime!
[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

# Even faster local development. Compile dependencies optimized once, but
# incrementally rebuild this crate super quickly. Runtime performance is still
# usable for the current tests, but noticeably slower.
[profile.dev.package."*"]
opt-level = 3
