name: Tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: backend/target
          key: cargo-test-${{ hashFiles('backend/Cargo.lock') }}

      - name: Download test inputs
        run: |
          cd web/public

          mkdir osm
          cd osm
          wget https://assets.od2net.org/severance_pbfs/bristol.pbf
          wget https://assets.od2net.org/severance_pbfs/strasbourg.pbf

          cd ..
          mkdir boundaries
          cd boundaries
          wget https://assets.od2net.org/boundaries/bristol.geojson
          wget https://assets.od2net.org/boundaries/strasbourg.geojson

      - name: Run tests
        run: |
          cd backend
          cargo test --release
